[build]
  command = "npm install --legacy-peer-deps && npm install firebase --legacy-peer-deps && npm run build"
  publish = "out"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
